title: /hello-worllllll
description: aprenderemos a usar esta herramienta
template:
  repo: hello-worllllll-template
  name: hello-worllllll
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
